# Site settings
title: Loren Zut
url: "" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/social.jpg # be sure to change this image

# Contact
email: "hey@lorenzut.com" # This is my real email address. Please don't email me.

# Use this for production
sass:
  sass_dir: _css
  style: compressed