# Site settings
title: Patrick Lorenzut
tagline: A Radically Marginal Human
url: "https://lorenzut.com" # The base hostname & protocol for your site. Use it if you need absolute URL's
author: "Patrick Lorenzut"

# Social
socialimg: /img/social.jpg # be sure to change this image

# Contact
email: "patrick.lorenzut@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
sass:
  sass_dir: css
  style: compressed

collections:
  fascism:
    output: true
    permalink: /:collection/:title

plugins:
  - jekyll-feed

feed:
  collections:
    - fascism